import type { Article } from '@/types/article'

/**
 * 内置名人名言库数据
 * 包含古今中外名人名言，用于打字练习
 */
export const QUOTES_DATA: Omit<Article, 'sentences' | 'createdAt'>[] = [
  {
    id: 'quote-tianxingjian',
    key: 'quote-tianxingjian',
    title: '天行健',
    description: '《周易》',
    content: '天行健，君子以自强不息。',
    source: 'builtin',
  },
  {
    id: 'quote-dishishikun',
    key: 'quote-dishishikun',
    title: '地势坤',
    description: '《周易》',
    content: '地势坤，君子以厚德载物。',
    source: 'builtin',
  },
  {
    id: 'quote-xuehaiwuya',
    key: 'quote-xuehaiwuya',
    title: '学海无涯',
    description: '《增广贤文》',
    content: '书山有路勤为径，学海无涯苦作舟。',
    source: 'builtin',
  },
  {
    id: 'quote-sanxingxing',
    key: 'quote-sanxingxing',
    title: '三人行',
    description: '《论语》',
    content: '三人行，必有我师焉。',
    source: 'builtin',
  },
  {
    id: 'quote-xuerusiji',
    key: 'quote-xuerusiji',
    title: '学如不及',
    description: '《论语》',
    content: '学如不及，犹恐失之。',
    source: 'builtin',
  },
  {
    id: 'quote-wenjiruowu',
    key: 'quote-wenjiruowu',
    title: '温故知新',
    description: '《论语》',
    content: '温故而知新，可以为师矣。',
    source: 'builtin',
  },
  {
    id: 'quote-zhibuzhuxing',
    key: 'quote-zhibuzhuxing',
    title: '知行合一',
    description: '王阳明',
    content: '知是行之始，行是知之成。',
    source: 'builtin',
  },
  {
    id: 'quote-luoyeoguien',
    key: 'quote-luoyeoguien',
    title: '落叶归根',
    description: '《增广贤文》',
    content: '树高千尺，叶落归根。',
    source: 'builtin',
  },
  {
    id: 'quote-qinfenbuchuo',
    key: 'quote-qinfenbuchuo',
    title: '勤奋不辍',
    description: '《增广贤文》',
    content: '一年之计在于春，一日之计在于晨。',
    source: 'builtin',
  },
  {
    id: 'quote-duomianqianxu',
    key: 'quote-duomianqianxu',
    title: '谦受益',
    description: '《尚书》',
    content: '满招损，谦受益。',
    source: 'builtin',
  },
  {
    id: 'quote-chizhijiu',
    key: 'quote-chizhijiu',
    title: '持之以恒',
    description: '《荀子》',
    content: '锲而不舍，金石可镂。',
    source: 'builtin',
  },
  {
    id: 'quote-jingyiqiujing',
    key: 'quote-jingyiqiujing',
    title: '精益求精',
    description: '《论语》',
    content: '如切如磋，如琢如磨。',
    source: 'builtin',
  },
  {
    id: 'quote-houjibofa',
    key: 'quote-houjibofa',
    title: '厚积薄发',
    description: '苏轼',
    content: '博观而约取，厚积而薄发。',
    source: 'builtin',
  },
  {
    id: 'quote-zhishanzhimei',
    key: 'quote-zhishanzhimei',
    title: '止于至善',
    description: '《大学》',
    content: '大学之道，在明明德，在亲民，在止于至善。',
    source: 'builtin',
  },
  {
    id: 'quote-shenanduxing',
    key: 'quote-shenanduxing',
    title: '慎独修身',
    description: '《中庸》',
    content: '莫见乎隐，莫显乎微，故君子慎其独也。',
    source: 'builtin',
  },
  {
    id: 'quote-tiandaochouqin',
    key: 'quote-tiandaochouqin',
    title: '天道酬勤',
    description: '《易经》',
    content: '天道酬勤，厚德载物。',
    source: 'builtin',
  },
  {
    id: 'quote-gongbukeju',
    key: 'quote-gongbukeju',
    title: '功亏一篑',
    description: '《尚书》',
    content: '为山九仞，功亏一篑。',
    source: 'builtin',
  },
  {
    id: 'quote-jianxiansicji',
    key: 'quote-jianxiansicji',
    title: '见贤思齐',
    description: '《论语》',
    content: '见贤思齐焉，见不贤而内自省也。',
    source: 'builtin',
  },
  {
    id: 'quote-yixinhuanyou',
    key: 'quote-yixinhuanyou',
    title: '以心换心',
    description: '《论语》',
    content: '己所不欲，勿施于人。',
    source: 'builtin',
  },
  {
    id: 'quote-guoerrbujiu',
    key: 'quote-guoerrbujiu',
    title: '过而不改',
    description: '《论语》',
    content: '过而不改，是谓过矣。',
    source: 'builtin',
  },
  {
    id: 'quote-minbuhanyou',
    key: 'quote-minbuhanyou',
    title: '贫而无谄',
    description: '《论语》',
    content: '贫而无谄，富而无骄。',
    source: 'builtin',
  },
  {
    id: 'quote-renzheryuren',
    key: 'quote-renzheryuren',
    title: '仁者爱人',
    description: '《孟子》',
    content: '仁者爱人，有礼者敬人。',
    source: 'builtin',
  },
  {
    id: 'quote-debugu',
    key: 'quote-debugu',
    title: '得道多助',
    description: '《孟子》',
    content: '得道者多助，失道者寡助。',
    source: 'builtin',
  },
  {
    id: 'quote-tianjiangdaren',
    key: 'quote-tianjiangdaren',
    title: '天降大任',
    description: '《孟子》',
    content: '天将降大任于斯人也，必先苦其心志，劳其筋骨。',
    source: 'builtin',
  },
  {
    id: 'quote-buhuanbujun',
    key: 'quote-buhuanbujun',
    title: '不患寡患不均',
    description: '《论语》',
    content: '不患寡而患不均，不患贫而患不安。',
    source: 'builtin',
  },
  {
    id: 'quote-zhibuzedou',
    key: 'quote-zhibuzedou',
    title: '知足常乐',
    description: '《道德经》',
    content: '知足者富，强行者有志。',
    source: 'builtin',
  },
  {
    id: 'quote-shangshannruoshui',
    key: 'quote-shangshannruoshui',
    title: '上善若水',
    description: '《道德经》',
    content: '上善若水，水善利万物而不争。',
    source: 'builtin',
  },
  {
    id: 'quote-daokeyidao',
    key: 'quote-daokeyidao',
    title: '道可道',
    description: '《道德经》',
    content: '道可道，非常道。名可名，非常名。',
    source: 'builtin',
  },
  {
    id: 'quote-wuqiongdeyu',
    key: 'quote-wuqiongdeyu',
    title: '无穷之路',
    description: '《庄子》',
    content: '吾生也有涯，而知也无涯。',
    source: 'builtin',
  },
  {
    id: 'quote-tiandiyumou',
    key: 'quote-tiandiyumou',
    title: '天地与谋',
    description: '《孙子兵法》',
    content: '知己知彼，百战不殆。',
    source: 'builtin',
  },
  {
    id: 'quote-shaozhuangbuni',
    key: 'quote-shaozhuangbuni',
    title: '少壮不努力',
    description: '《长歌行》',
    content: '少壮不努力，老大徒伤悲。',
    source: 'builtin',
  },
  {
    id: 'quote-haierbuchuo',
    key: 'quote-haierbuchuo',
    title: '学而不厌',
    description: '《论语》',
    content: '学而不厌，诲人不倦。',
    source: 'builtin',
  },
]
