import type { BuiltinArticleDef } from '@/types/article'

/**
 * 内置名人名言库数据
 * 包含古今中外名人名言，用于打字练习
 * 采用懒加载设计：元数据立即加载，内容按需获取
 */
export const QUOTES_DATA: BuiltinArticleDef[] = [
  {
    id: 'quote-tianxingjian',
    key: 'quote-tianxingjian',
    title: '天行健',
    description: '《周易》',
    getContent: () => '天行健，君子以自强不息。',
  },
  {
    id: 'quote-dishishikun',
    key: 'quote-dishishikun',
    title: '地势坤',
    description: '《周易》',
    getContent: () => '地势坤，君子以厚德载物。',
  },
  {
    id: 'quote-xuehaiwuya',
    key: 'quote-xuehaiwuya',
    title: '学海无涯',
    description: '《增广贤文》',
    getContent: () => '书山有路勤为径，学海无涯苦作舟。',
  },
  {
    id: 'quote-sanxingxing',
    key: 'quote-sanxingxing',
    title: '三人行',
    description: '《论语》',
    getContent: () => '三人行，必有我师焉。',
  },
  {
    id: 'quote-xuerusiji',
    key: 'quote-xuerusiji',
    title: '学如不及',
    description: '《论语》',
    getContent: () => '学如不及，犹恐失之。',
  },
  {
    id: 'quote-wenjiruowu',
    key: 'quote-wenjiruowu',
    title: '温故知新',
    description: '《论语》',
    getContent: () => '温故而知新，可以为师矣。',
  },
  {
    id: 'quote-zhibuzhuxing',
    key: 'quote-zhibuzhuxing',
    title: '知行合一',
    description: '王阳明',
    getContent: () => '知是行之始，行是知之成。',
  },
  {
    id: 'quote-luoyeoguien',
    key: 'quote-luoyeoguien',
    title: '落叶归根',
    description: '《增广贤文》',
    getContent: () => '树高千尺，叶落归根。',
  },
  {
    id: 'quote-qinfenbuchuo',
    key: 'quote-qinfenbuchuo',
    title: '勤奋不辍',
    description: '《增广贤文》',
    getContent: () => '一年之计在于春，一日之计在于晨。',
  },
  {
    id: 'quote-duomianqianxu',
    key: 'quote-duomianqianxu',
    title: '谦受益',
    description: '《尚书》',
    getContent: () => '满招损，谦受益。',
  },
  {
    id: 'quote-chizhijiu',
    key: 'quote-chizhijiu',
    title: '持之以恒',
    description: '《荀子》',
    getContent: () => '锲而不舍，金石可镂。',
  },
  {
    id: 'quote-jingyiqiujing',
    key: 'quote-jingyiqiujing',
    title: '精益求精',
    description: '《论语》',
    getContent: () => '如切如磋，如琢如磨。',
  },
  {
    id: 'quote-houjibofa',
    key: 'quote-houjibofa',
    title: '厚积薄发',
    description: '苏轼',
    getContent: () => '博观而约取，厚积而薄发。',
  },
  {
    id: 'quote-zhishanzhimei',
    key: 'quote-zhishanzhimei',
    title: '止于至善',
    description: '《大学》',
    getContent: () => '大学之道，在明明德，在亲民，在止于至善。',
  },
  {
    id: 'quote-shenanduxing',
    key: 'quote-shenanduxing',
    title: '慎独修身',
    description: '《中庸》',
    getContent: () => '莫见乎隐，莫显乎微，故君子慎其独也。',
  },
  {
    id: 'quote-tiandaochouqin',
    key: 'quote-tiandaochouqin',
    title: '天道酬勤',
    description: '《易经》',
    getContent: () => '天道酬勤，厚德载物。',
  },
  {
    id: 'quote-gongbukeju',
    key: 'quote-gongbukeju',
    title: '功亏一篑',
    description: '《尚书》',
    getContent: () => '为山九仞，功亏一篑。',
  },
  {
    id: 'quote-jianxiansicji',
    key: 'quote-jianxiansicji',
    title: '见贤思齐',
    description: '《论语》',
    getContent: () => '见贤思齐焉，见不贤而内自省也。',
  },
  {
    id: 'quote-yixinhuanyou',
    key: 'quote-yixinhuanyou',
    title: '以心换心',
    description: '《论语》',
    getContent: () => '己所不欲，勿施于人。',
  },
  {
    id: 'quote-guoerrbujiu',
    key: 'quote-guoerrbujiu',
    title: '过而不改',
    description: '《论语》',
    getContent: () => '过而不改，是谓过矣。',
  },
  {
    id: 'quote-minbuhanyou',
    key: 'quote-minbuhanyou',
    title: '贫而无谄',
    description: '《论语》',
    getContent: () => '贫而无谄，富而无骄。',
  },
  {
    id: 'quote-renzheryuren',
    key: 'quote-renzheryuren',
    title: '仁者爱人',
    description: '《孟子》',
    getContent: () => '仁者爱人，有礼者敬人。',
  },
  {
    id: 'quote-debugu',
    key: 'quote-debugu',
    title: '得道多助',
    description: '《孟子》',
    getContent: () => '得道者多助，失道者寡助。',
  },
  {
    id: 'quote-tianjiangdaren',
    key: 'quote-tianjiangdaren',
    title: '天降大任',
    description: '《孟子》',
    getContent: () => '天将降大任于斯人也，必先苦其心志，劳其筋骨。',
  },
  {
    id: 'quote-buhuanbujun',
    key: 'quote-buhuanbujun',
    title: '不患寡患不均',
    description: '《论语》',
    getContent: () => '不患寡而患不均，不患贫而患不安。',
  },
  {
    id: 'quote-zhibuzedou',
    key: 'quote-zhibuzedou',
    title: '知足常乐',
    description: '《道德经》',
    getContent: () => '知足者富，强行者有志。',
  },
  {
    id: 'quote-shangshannruoshui',
    key: 'quote-shangshannruoshui',
    title: '上善若水',
    description: '《道德经》',
    getContent: () => '上善若水，水善利万物而不争。',
  },
  {
    id: 'quote-daokeyidao',
    key: 'quote-daokeyidao',
    title: '道可道',
    description: '《道德经》',
    getContent: () => '道可道，非常道。名可名，非常名。',
  },
  {
    id: 'quote-wuqiongdeyu',
    key: 'quote-wuqiongdeyu',
    title: '无穷之路',
    description: '《庄子》',
    getContent: () => '吾生也有涯，而知也无涯。',
  },
  {
    id: 'quote-tiandiyumou',
    key: 'quote-tiandiyumou',
    title: '天地与谋',
    description: '《孙子兵法》',
    getContent: () => '知己知彼，百战不殆。',
  },
  {
    id: 'quote-shaozhuangbuni',
    key: 'quote-shaozhuangbuni',
    title: '少壮不努力',
    description: '《长歌行》',
    getContent: () => '少壮不努力，老大徒伤悲。',
  },
  {
    id: 'quote-haierbuchuo',
    key: 'quote-haierbuchuo',
    title: '学而不厌',
    description: '《论语》',
    getContent: () => '学而不厌，诲人不倦。',
  },
  {
    id: 'quote-minweibangben',
    key: 'quote-minweibangben',
    title: '民为邦本',
    description: '《尚书》',
    getContent: () => '民惟邦本，本固邦宁。',
  },
  {
    id: 'quote-zhixingheyi',
    key: 'quote-zhixingheyi',
    title: '知行并进',
    description: '《礼记》',
    getContent: () => '博学之，审问之，慎思之，明辨之，笃行之。',
  },
  {
    id: 'quote-shanxiaoershou',
    key: 'quote-shanxiaoershou',
    title: '善小亦为',
    description: '《三国志》',
    getContent: () => '勿以恶小而为之，勿以善小而不为。',
  },
  {
    id: 'quote-jianrenzhiben',
    key: 'quote-jianrenzhiben',
    title: '见仁见智',
    description: '《周易》',
    getContent: () => '仁者见之谓之仁，智者见之谓之智。',
  },
  {
    id: 'quote-shibukeyishi',
    key: 'quote-shibukeyishi',
    title: '士不可夺志',
    description: '《论语》',
    getContent: () => '三军可夺帅也，匹夫不可夺志也。',
  },
  {
    id: 'quote-zhiyuzhixue',
    key: 'quote-zhiyuzhixue',
    title: '知止后定',
    description: '《大学》',
    getContent: () => '知止而后有定，定而后能静，静而后能安，安而后能虑，虑而后能得。',
  },
  {
    id: 'quote-jianxianqisi',
    key: 'quote-jianxianqisi',
    title: '兼听则明',
    description: '《资治通鉴》',
    getContent: () => '兼听则明，偏信则暗。',
  },
  {
    id: 'quote-qiongzebiantong',
    key: 'quote-qiongzebiantong',
    title: '穷则思变',
    description: '《周易》',
    getContent: () => '穷则变，变则通，通则久。',
  },
  {
    id: 'quote-zhiqingxingyuan',
    key: 'quote-zhiqingxingyuan',
    title: '志行高远',
    description: '诸葛亮',
    getContent: () => '非淡泊无以明志，非宁静无以致远。',
  },
  {
    id: 'quote-chengxinyizheng',
    key: 'quote-chengxinyizheng',
    title: '诚信立身',
    description: '《论语》',
    getContent: () => '人而无信，不知其可也。',
  },
]
